# Enable homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# Swap ~ and § keys
hidutil property --set '{"UserKeyMapping":[{"HIDKeyboardModifierMappingSrc":0x700000035,"HIDKeyboardModifierMappingDst":0x700000064},{"HIDKeyboardModifierMappingSrc":0x700000064,"HIDKeyboardModifierMappingDst":0x700000035}]}'

export CLICOLOR=1

# suppress annoying default shell warning
export BASH_SILENCE_DEPRECATION_WARNING=1

clear

[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion
